### ISSUE TITLE
Dont work in newer versions of Font Awesome

### ISSUE THREAD

**Issue by isaacmeira** [pguso/js-plugin-circliful#164]
i´ve tried on newer versions of Font awesome and simply don´t work on then.
the icons dont show as expected

**Comment by rm-code** [comment]
@isaacmeira 
I solved it by changing https://github.com/pguso/jquery-plugin-circliful/blob/master/css/jquery.circliful.css#L38

to
```css
svg .icon {
  font-family: 'Font Awesome 5 Free';
}
```

@pguso 
I'll see if I can submit a PR later on which allows us to set the font family as a parameter.
